kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
  labels: 
    app: hello-node
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi