apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  type: LoadBalancer
  selector:
      app: hello-node
  ports:
  - name: hello-node
    port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  serviceName: hello-node
  replicas: 3
  template:
    metadata:
      name: hello-node
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: hello-node:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: task-pv-storage
          mountPath: /usr/app
      # volumes:
      #   - name: task-pv-storage
      #     hostPath:
      #       path: /var/dist/

      #   volumeMounts:
      #       - name: task-pv-storage
      #         mountPath: /usr/app
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
