apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
  labels:
    app: hello-node
spec:
  type: LoadBalancer
  selector:
      app: hello-node
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-deployment
  labels:
    app: hello-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: hello-node:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: task-pv-storage
              mountPath: /usr/app
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim